-
  name: 'Base config for installing Gluster on all machines'
  hosts: all
  vars_files:
    - local-vars.yml
  tasks:
    -
      name: 'Registering credentials'
      redhat_subscription:
        state: present
        username: '{{username}}'
        password: '{{password}}'
        pool_ids: '{{pool}}'
        syspurpose:
          role: '{{role}}'
    -
      name: 'Disabling all the repos'
      rhsm_repository: 'name=* state=disabled'
