-
  name: 'Enabling firewall rules for gluster'
  hosts: rhels
  vars_files:
    - local-vars.yml
  tasks:
    -
      name: 'Start glusterd'
      systemd: 'state=started name=glusterd'
    -
      name: 'Start firewalld'
      systemd: 'state=started name=firewalld'
    -
      name: 'Adding firewall rules'
      command: 'firewall-cmd --zone=public --add-service={{item}}'
      with_items: '{{firewall}}'
    -
      name: 'Adding firewall rules permanently'
      command: 'firewall-cmd --zone=public --permanent --add-service={{item}}'
      with_items: '{{firewall}}'
