-
  name: 'Installing Gluster on RHEL 7 Servers'
  hosts: rhel7t
  vars_files:
    - local-vars.yml
    # - local-links.yml
  tasks:
    -
      name: 'Enabling required repos'
      rhsm_repository: 'name={{_7tb}} state=enabled'
    -
      name: 'Install yum-config-manager'
      yum: 'name=yum-utils state=present'
    # -
    #   name: 'Add local repo links'
    #   command: 'yum-config-manager --add-repo="{{_7sl}}"'
    # -
    #   name: 'Clean all cache'
    #   command: 'yum clean all'
    -
      name: 'yum Update the system'
      yum: 'name=* state=latest'
