-
  name: 'Installing Gluster on RHEL 7 Clients'
  hosts: rhel7c
  vars_files:
    - local-vars.yml
    # - local-links.yml
  tasks:
    -
      name: 'Enabling required repos'
      rhsm_repository: 'name={{_7cb}} state=enabled'
    -
      name: 'Install yum-config-manager'
      yum: 'name=yum-utils state=present'
    # -
    #   name: 'Add local repo links'
    #   command: 'yum-config-manager --add-repo="{{_7cl}}"'
    # -
    #   name: 'Clean all cache'
    #   command: 'yum clean all'
    -
      name: 'yum Update the system'
      yum: 'name=* state=latest'
    -
      name: 'Install required packages'
      yum: 'name={{_7cp}} state=latest'
      # yum: 'name={{_7cp}} state=present disable_gpg_check=yes'
