-
  name: 'Installing Gluster on RHEL 8 Clients'
  hosts: 8c
  vars_files:
    - vars.yml
    - local_links.yml
  tasks:
    -
      name: 'Enabling required repos'
      rhsm_repository: 'name={{_8cb}} state=enabled'
    -
      name: 'Add local repo links'
      command: 'dnf config-manager --add-repo="{{_8cl}}"'
    -
      name: 'Clean all cache'
      command: 'dnf clean all'
    -
      name: 'Install required packages'
      yum: 'name={{_8cp}} state=present disable_gpg_check=yes'

